exports.FRIEND_ACCEPTED = 'ACCEPTED';
exports.FRIEND_PENDING = 'PENDING';

exports.STATUS_FRIEND = 'FRIEND';
exports.STATUS_REQUESTER = 'REQUESTER';
exports.STATUS_ACCEPTER = 'ACCEPTER';
exports.STATUS_UNKNOWN = 'UNKNOWN';
exports.STATUS_ME = 'ME';
